config/routes.rb
TrainessExam::Application.routes.draw do
  devise_for :users, path_names: { sign_up: "register" }
  
  root to: "main#index"

  resources :posts, only: [:index, :show, :new, :create, :destroy] do
    collection do
      post :like
      post :unlike
    end
  end

  resources :comments, only: [:create, :show], defaults: { format: :json }
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  acts_as_api
  attr_accessible :comment, :post_id, :user_id

  belongs_to :user
  belongs_to :post

  validates_presence_of :comment, :post_id, :user_id

  api_accessible :post_details do |template|
    template.add :comment
    template.add :username
    template.add :userid
    template.add :created_at
    template.add :updated_at
  end

  def username
    self.user.username
  end

  def userid
    self.user.id
  end
  
end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :post_id, :user_id
  
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :user_id, scope: :post_id  
end

app/models/post.rb
class Post < ActiveRecord::Base
  acts_as_api

  attr_accessible :author_id, :content, :title, :link

  belongs_to :author, class_name: User, foreign_key: :author_id
  has_many :likes
  has_many :comments

  validates_presence_of :content, :title, :author_id
  validates :content, length: { minimum: 140, message: "Please be more descriptive with the message" }
  validates :title, uniqueness: { message: "This post already exists" }
  validates :link, format: { 
    with: URI::regexp(%w(http https)), message: "Please enter valid link",
    allow_blank: true
  }

  default_scope order('created_at DESC')

  api_accessible :post_details do |template|
    template.add :id
    template.add :title
    template.add :content
    template.add :created_at
    template.add :updated_at
    template.add :pretty_print_likes
    template.add :comments
    template.add :author
  end

  def pretty_print_likes
    if likes.count > 0
      likes_string = "<i class='icon-thumbs-up'></i>"
      likes_string += "#{likes.first.user.username}"
      likes_string += " and other #{likes.count - 1}" unless likes.count == 1
      likes_string += " likes this."
    else
      "<i class='icon-thumbs-up'></i>Be the first of your friends to like this."
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_api
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  has_many :posts, foreign_key: :author_id
  has_many :likes
  has_many :comments
  
  validates_presence_of :username

  api_accessible :post_details do |template|
    template.add :id
    template.add :email
    template.add :username
    template.add :created_at
    template.add :updated_at
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  self.responder = ActsAsApi::Responder
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  respond_to :json

  def create
    @comment = Comment.new(post_id: params[:post_id], user_id: current_user.id, comment: params[:comment])
    if @comment.save
      respond_with(@comment, api_template: :post_details)
    else
      respond_with(@comment.errors, status: :unprocessable_entity, message: "We're sorry but something went wrong, try later")
    end
  end

  def show
    @comment = Comment.find(params[:id])
    respond_with(@comment, api_template: :post_details)
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all
    respond_to do |format|
      format.html
      format.json { render_for_api :post_details, json: @posts }
    end
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(params[:post].merge(author_id: current_user.id))
    respond_to do |format|
      if @post.save
        flash[:success] = "Successfully created new post #{@post.title}"
        format.html { redirect_to posts_path }
      else
        format.html { render :new }
      end
    end
  end

  def show
    @post = Post.find(params[:id])
    respond_to do |format|
      format.json { render_for_api :post_details, json: @post }
    end
  end

  def destroy
    @post = Post.find(params[:id])
    respond_to do |format|
      if @post.delete
        flash[:success] = "Successfully deleted new post #{@post.title}"
        format.html { redirect_to posts_path }
      else
        flash[:alert] = "Could not delete post: #{@post.title}, try again later"
        format.html { redirect_to posts_path }
      end
    end
  end

  def like
    @like = Like.new(post_id: params[:post_id], user_id: current_user.id)
    respond_to do |format|
      if @like.save
        @post = Post.find(params[:post_id])
        format.json { render json: { status: 200, message: @post.pretty_print_likes } }
      else
        format.json { render json: { status: 500, message: "Internal server error" } }
      end
    end
  end

  def unlike
    @like = Like.where(post_id: params[:post_id], user_id: current_user.id).shift
    respond_to do |format|
      if @like.destroy
        @post = Post.find(params[:post_id])
        format.json { render json: { status: 200, message: @post.pretty_print_likes, likes_count: @post.likes.count } }
      else
        format.json { render json: { status: 500, message: "Internal server error" } }
      end
    end
  end

  private
  
  def not_allowed_to_destroy_post
    flash[:alert] = "You're not allowed to destroy this post"
    redirect_to posts_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_flash_messages.html.haml
- flash.each do |key, value|
  - unless value.blank?
    %div{ class: "flash alert alert-#{key}"}
      %button(type="button" class="close" data-dismiss="alert")x
      = value

app/views/layouts/_menu.html.haml
%ul.nav.nav-pills
  %li{ class: "#{"active" if params[:controller] == "main"}"}= link_to "Index", root_path
  %li{ class: "#{"active" if params[:controller] == "posts"}"}= link_to "Posts", posts_path
  - if user_signed_in?
    %li{ style: "padding-top:8px;" }
      Hello!
      = current_user.username
    %li= link_to "Sign out", destroy_user_session_path, method: 'delete'
  - else
    %li{ style: "padding-top:8px;" } You're not logged in
    %li= link_to "Sign in", new_user_session_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blog
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    - if user_signed_in?
      %input.fn-current-user{ type: 'hidden', value: "#{current_user.to_json }" }
    - else
      %input.fn-current-user{ type: 'hidden', value: "#{{message: 'Not signed in...'}.to_json}" }

    = render 'layouts/menu'
    = render 'layouts/flash_messages'
    .container
      = yield

app/views/posts/_form.html.haml
= form_for @post, html: { class: "form-horizontal" } do |f|
  -if @post.errors.any?
    %h2
      = pluralize(@post.errors.count, "error" )
      Prohibited this article from being saved
    %ul
      - @post.errors.full_messages.each do |msg|
        %li= msg
  .control-group
    = f.label :title, class: 'control-label'
    .controls
      = f.text_field :title
  .control-group
    = f.label :content, class: 'control-label'
    .controls
      = f.text_area :content
  .control-group
    = f.label :link, class: 'control-label'
    .controls
      = f.text_field :link
  .control-group
    .controls
      = f.submit @post.new_record? ? "Create post" : "Update post", class: 'btn'

app/views/posts/_post.html.haml
.fn-post.hero-unit
  %input{ type: 'hidden', class: 'fn-id', value: "#{post.id}"}
  %h3
    %a.fn-show-post= post.title
  %p= post.content
  
  By:
  %a{ href: "/authors/#{post.author_id}" }= post.author.username
  - if user_signed_in?
    - unless current_user.posts.where(id: post.id).shift.nil?
      |
      = link_to "Delete post", post_path(post.id), method: 'delete'

    - if user_signed_in?
      |
      %span.fn-like-link
        - if current_user.likes.where(post_id: post.id).shift.nil?
          %a.fn-like Like
        - else
          %a.fn-unlike Unlike
      %br
      .fn-like-message
        = post.pretty_print_likes.html_safe

app/views/posts/index.html.haml
.page-header
  %h1 Listing posts

.fn-posts-container
  = render 'templates/post_modal'
  = render partial: 'post', collection: @posts

= link_to "Create new post", new_post_path, class: "btn btn-inverse" if user_signed_in?

app/views/posts/new.html.haml
.page-header
  %h1 Create new post

= render 'form'

app/views/templates/_post.html.haml
.fn-post.hero-unit
  %input{ type: 'hidden', class: 'fn-id', value: "#{post.id}"}
  %h3
    %a.fn-show-post {{ title }}
  %p= {{ content }}
  
  By:
  %a{ href: "/authors/#{post.author_id}" }= {{ author.username }}
  {{ #signedIn }}
    = link_to "Delete post", post_path(post.id), method: 'delete'
    |
    %span.fn-like-link
      - if current_user.likes.where(post_id: post.id).shift.nil?
        %a.fn-like Like
      - else
        %a.fn-unlike Unlike
    %br
    .fn-like-message
      = post.pretty_print_likes.html_safe

app/views/templates/_post_modal.html.haml
.fn-post-modal.modal.hide.fade
  .modal-header
    %input{ type: 'hidden', class: 'fn-post-id' }
    %button(type="button" class="close" data-dismiss="modal" aria-hidden="true")x
    %h3.fn-title
  .modal-body
    %p.fn-content
    %a.fn-author{ target: "blank" }
  %ul.fn-comments.breadcrumb
  %form.fn-create-comment
    %div.span1
    %textarea{ class: "fn-comment-text input-large span5" }
  .modal-footer
    %p.fn-error{ style: 'color:red; float:left;' }
    %a(href="#" class="btn" data-dismiss="modal")Close

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>